language: generic

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_install:
  - mysql -u root -e 'create database speakrdb;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
# Install .net using linux CLI commands
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview2-1-003177

script:
  - dotnet restore
  - dotnet build src/Speakr.TalksApi
  - dotnet build tests/Speakr.TalksApi.Tests
  - dotnet test tests/Speakr.TalksApi.Tests
  - dotnet test tests/Speakr.TalksApi.AcceptanceTests

before_deploy:
  - zip -r $(date +'TalksApi-%F').zip *
  - mkdir -p CodeDeploy_Artifacts
  - mv $(date +'TalksApi-%F').zip CodeDeploy_Artifacts/$(date +'TalksApi-%F').zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: eu-west-1
    bucket: speakr-travisbuilds
    local_dir: CodeDeploy_Artifacts
    skip_cleanup: true
    upload-dir: TalksApi
    on: &2
        branch: production
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: eu-west-1
    bucket: speakr-travisbuilds
    key: TalksApi/$(date +'TalksApi-%F').zip
    application: speakr-talksapi-codedeploy
    deployment_group: speakr-talksapi-codedeploy-Fleet
    on: *2
